#!/bin/sh

CA_ARTIFACTORY_URL="https://bin.gov.pf/artifactory/ca"
CA_CERTINOMIS_URL="https://www.certinomis.fr/publi/cer"
CA_CERTIGNA_URL="http://autorite.certigna.fr"

CERT_URLS="$CA_ARTIFACTORY_URL/cadsi-prod.pem \
    $CA_CERTINOMIS_URL/AC_Racine_G3.cer \
    $CA_CERTINOMIS_URL/AC_2017_web.pem.cer \
    $CA_CERTINOMIS_URL/AC_CERTINOMIS_SSL.cer \
    $CA_CERTINOMIS_URL/AC_AGENTS.cer \
    $CA_CERTIGNA_URL/certignarootca.crt \
    $CA_CERTIGNA_URL/servicesca.crt \
    $CA_CERTIGNA_URL/servicesca_rootca.crt \
    $CA_ARTIFACTORY_URL/Bundle_certificat_certigna.crt \
    $CA_ARTIFACTORY_URL/CertignaServerAuthenticationOVCPCAG1.crt"
    
for cert_url in $CERT_URLS
do
    cert_file="$(basename "$cert_url")"
    cert_path="/usr/local/share/ca-certificates/$cert_file"

    curl "$cert_url" -o "$cert_path"

    # Badly formatted certs break the entire file in alpine
    # Adds an eol char at the end of the file if not already present
    sed -i -e '$a\' "$cert_path"
done

openssl x509 -in /usr/local/share/ca-certificates/cadsi-prod.pem -out /usr/local/share/ca-certificates/cadsi-prod.crt
rm -f /usr/local/share/ca-certificates/cadsi-prod.pem

update-ca-certificates
