name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [latest, buster, jessie, stretch]
    env:
      repo: "govpf/debian"
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build and push
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}
